# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: utf7.1 CI

# Global environment variable to allow using unsecure Node.js versions
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  node-10:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 10.x
      uses: actions/setup-node@v4
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: npm i
    - run: npm ci
    - name: Build project
      run: npm run build --if-present
    - name: Run tests
      run: npm test
      env:
        CI: true
  node-12:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 12.x
      uses: actions/setup-node@v4
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm i
    - run: npm ci
    - name: Build project
      run: npm run build --if-present
    - name: Run tests
      run: npm test
      env:
        CI: true

  node-14:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 14.x
      uses: actions/setup-node@v4
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm i
    - run: npm ci
    - name: Build project
      run: npm run build --if-present
    - name: Run tests
      run: npm test
      env:
        CI: true



  node-18:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm i
    - run: npm ci
    - name: Build project
      run: npm run build --if-present
    - name: Run tests
      run: npm test
      env:
        CI: true

  node-20:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm i
    - run: npm ci
    - name: Build project
      run: npm run build --if-present
    - name: Run tests
      run: npm test
      env:
        CI: true
